apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: PluginPostSponsorCard
spec:
  enabled: true
  requires: ">=2.8.0"
  author:
    name: Charlie Liu
    website: https://www.wggznb.top
  logo: logo.svg
  settingName: plugin-post-sponsor-card-settings
  configMapName: plugin-post-sponsor-card-configmap
  homepage: https://github.com/liuchangfitcloud/plugin-article-bottom-panel
  displayName: "文章赞赏"
  description: "文章赞赏插件"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/halo-dev/plugin-starter/blob/main/LICENSE"
